services:

  app:
    build: .
    image: speak-shine-app:latest
    container_name: speak-shine-app

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3001:3001"

    networks:
      - speakshine-network

networks:
  speakshine-network:
