[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg"]

[phases.install]
cmds = [
  "npm install --omit=dev --omit=optional --ignore-scripts",
  "npm install --prefix frontend --omit=dev"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]

[start]
cmd = "NODE_ENV=production node api/server.js"
