[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.webapp.toml"

[deploy]
startCommand = "NODE_ENV=production node api/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
