name: Speak-Shine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with Rollback
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/Speak-Shine-

            echo "Pull latest code"
            git pull origin main

            echo "Backup current container"
            docker rename speak-shine-container speak-shine-backup || true

            echo "Build new image"
            docker build -t speak-shine .

            echo "Run new container"
            docker run -d \
              --env-file .env \
              -p 3001:3001 \
              --name speak-shine-container \
              speak-shine

            echo "Waiting for app health check..."
            sleep 15

            if docker ps | grep speak-shine-container; then
              echo "New deployment successful"

              docker rm -f speak-shine-backup || true
            else
              echo "Deployment failed. Rolling back..."

              docker rm -f speak-shine-container || true

              docker rename speak-shine-backup speak-shine-container

              docker start speak-shine-container

              exit 1
            fi



# name: Speak-Shine Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to AWS EC2
#         uses: appleboy/ssh-action@master

#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_KEY }}

#           script: |
#             cd ~/Speak-Shine-

#             git pull origin main

#             npm install

#             pm2 restart speak-shine