name: Speak-Shine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
            docker build \
            --platform linux/amd64 \
            -t speak-shine .

      - name: Tag Docker Image
        run: |
          docker tag speak-shine:latest \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |

            set -e

            cd ~/Speak-Shine-

            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            git pull origin main

            echo "================================="
            echo "Backup current compose file"
            echo "================================="

            cp docker-compose.yml docker-compose.backup.yml

            echo "================================="
            echo "Login to AWS ECR"
            echo "================================="

            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin \
            ${{ steps.login-ecr.outputs.registry }}

            echo "================================="
            echo "Pull latest Docker image"
            echo "================================="

            docker pull \
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

            echo "================================="
            echo "Backup current running containers"
            echo "================================="

            docker compose down || true

            echo "================================="
            echo "Start updated containers"
            echo "================================="

            docker compose up -d --force-recreate

            echo "================================="
            echo "Waiting for containers"
            echo "================================="

            sleep 25

            echo "================================="
            echo "Container Status"
            echo "================================="

            docker ps -a

            echo "================================="
            echo "Checking App Health"
            echo "================================="

            if docker ps | grep speak-shine-app
            then

              echo "================================="
              echo "Deployment Successful"
              echo "================================="

              docker image prune -af || true

            else

              echo "================================="
              echo "Deployment Failed"
              echo "================================="

              echo "================================="
              echo "Container Logs"
              echo "================================="

              docker compose logs --tail=100

              echo "================================="
              echo "Rolling Back"
              echo "================================="

              docker compose down || true

              cp docker-compose.backup.yml docker-compose.yml

              docker compose up -d --force-recreate

              exit 1

            fi

            echo "================================="
            echo "Running Containers"
            echo "================================="

            docker ps

            echo "================================="
            echo "Docker Usage"
            echo "================================="

            docker system df

            echo "================================="
            echo "Deployment Completed"
            echo "================================="

            
# name: Speak-Shine Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to AWS EC2
#         uses: appleboy/ssh-action@master

#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_KEY }}

#           script: |
#             cd ~/Speak-Shine-

#             git pull origin main

#             npm install

#             pm2 restart speak-shine